### ISSUE TITLE
命令菜单当悬浮窗口调出来后，可以点击下层元素

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/tw-command-palette#11]
应该屏蔽一下事件冒泡
<img width="508" alt="截屏2022-05-21 13 36 53" src="https://user-images.githubusercontent.com/3746270/169637299-b89d2ed0-ea31-4b78-a256-f0b1588b8b55.png">

**Comment by oeyoews** [comment]
masklayer的z-index为9998, 正常情况下,下面的元素应该会被挡住, 鼠标事件是不会响应的吧, 但是你这个不知道为什么, 需要把pointer-events 去掉或者none改成auto, 才能修复这个问题 @linonetwo

**Comment by linonetwo** [comment]
但是问题不是能点到下面吗，不应该是加上这个防止点击？

**Comment by oeyoews** [comment]
pointer-event: none 是忽略当前元素的鼠标事件, 但是下层的子元素任然任然可以点击, 由于masklayer的z-index 高于故事河, 所以下层元素是被挡住的, 无法相应鼠标事件, 需要先加上一个pointer-envent: none; 相应鼠标事件, 当命令菜单打开的时候再移除pointer-envent: none;(masklayer在没有打开命令菜单的时候就已经渲染好了)
![image](https://github.com/tiddly-gittly/tw-command-palette/assets/72405338/92f66653-f090-4369-b317-04c47e1e7fdf)

**Comment by oeyoews** [comment]
https://neotw.oeyoewl.top/ 可以在这里看一下效果(部分样式使用tailwindcss改写)
