### ISSUE TITLE
在侧边栏放上搜索框，并替代默认搜索框

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/tw-command-palette#4]
![image](https://github.com/tiddly-gittly/tw-command-palette/assets/109711900/c1e78cd8-87e3-49fe-a322-88fbed94d58b)

主要我找不到这个条目在哪里，不知道怎么生成的。如果有一个静态条目的话，直接加个标签，修改掉默认搜索框就可以了。

https://github.com/tiddly-gittly/itonnote-theme/pull/6

这样也可以避免上述问题。

**Comment by dongrentianyu** [comment]
等放假了看有没有时间研究一下，最近估计没什么时间研究了。

**Comment by dongrentianyu** [comment]
不过我看太记侧边栏就附带了一个按钮。那也可以把这个东西放到太记的顶部。这样好像也可以的样子。但是那改起来就麻烦了。

**Comment by linonetwo** [comment]
现在命令菜单的设置里加了一个配置项，勾选才隐藏默认搜索。我之前忘了是在这边加的，我去把 Itonnote theme 里的去掉
